### ISSUE TITLE
Install fails due to missing release

### ISSUE THREAD

**Issue by dinjaya** [MrBretticus/hass-emerald-ems#28]
## System Information

version | core-2024.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | aarch64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1409
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 28.0 GB
disk_used | 5.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | green
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.7.2), Terminal & SSH (9.14.0), Get HACS (1.3.1), Samba share (12.3.2), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 9, 2024 at 02:10
-- | --
current_recorder_run | September 17, 2024 at 13:23
estimated_db_size | 14.94 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/mrbretticus/hass-emerald-ems/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Automatic Installation fails at step 6 during installation as there are no [github releases](https://github.com/MrBretticus/hass-emerald-ems/releases/). 

System message:
Downloading MrBretticus/hass-emerald-ems with version 8588ca9
failed with (Could not download, see log for details)

### Reproduction steps

1. Automatic Installation steps 1 to 5 works
2. Fails at step 6 while downloading Emerald EMS

### Debug logs

```text
2024-09-19 13:42:45.357 ERROR (MainThread) [custom_components.hacs] <Integration MrBretticus/hass-emerald-ems> Failed to download https://github.com/MrBretticus/hass-emerald-ems/releases/download/tags/8588ca9/hass_emerald_ems.zip
2024-09-19 13:42:45.357 ERROR (MainThread) [custom_components.hacs] <Integration MrBretticus/hass-emerald-ems> Downloading MrBretticus/hass-emerald-ems with version 8588ca9 failed with (Could not download, see log for details)
```

**Comment by dinjaya** [comment]
Please let me know if it is too early for me to try your integration or whether I should try the manual installation process.
I am using a Bluetooth dongle and don't have an esp32 so the other Emerald Energy Advisor integration from [WeekendWarrior1](https://github.com/WeekendWarrior1/emerald_electricity_advisor) does not work for me.
thanks :)

**Comment by MrBretticus** [comment]
Thanks for the interest @dinjaya and yes too early to try the integration. I'll get back to you once ready for testing.
